[package]
name = "advent-of-code-rs"
version = "0.1.0"
authors = ["Naum Azeredo <naumazeredo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
